version: "3.8"

volumes:
  chroot:

services:
  kali:
    image: kalilinux/kali-rolling
    privileged: true
    network_mode: "host"

    environment:
      - SSHD_LISTEN_ADDRESS=":2223"
      - SSHD_KEYS_URL="https://github.com/ferama.keys"
      # - SSHD_PASSWORD="admin123"
      - ROSPO_VERSION=v0.11.1/rospo-linux-amd64
      - USER=rospo
      - XRDP_PASSWORD=rospo

    volumes:
      - chroot:/data

    command:
      - /bin/bash
      - -c
      - |
        set -ex

        if [ ! -f /data/chroot-ready ]; then
          apt update
          apt install -y schroot debootstrap curl
          debootstrap kali-rolling /data

          curl -s -L https://github.com/ferama/rospo/releases/download/$${ROSPO_VERSION} -o /data/usr/local/bin/rospo
          chmod +x /data/usr/local/bin/rospo
          mkdir /data/etc/rospo

        # do not change indention here or bash will complain
        chroot /data /bin/bash <<EOT
          set -x
          echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list

          export DEBIAN_FRONTEND=noninteractive
          apt update
          apt install -y kali-linux-core

          apt install -y kali-desktop-xfce
          apt install -y xrdp net-tools

          adduser --gecos "" --disabled-password $${USER}
          echo "$${USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          usermod -a -G sudo $${USER}
        EOT
        fi

        cp /etc/hosts /data/etc/hosts

        mount proc /data/proc -t proc
        mount sysfs /data/sys -t sysfs
        mount -o bind /dev /data/dev/
        mount -t devpts pts /data/dev/pts/
        mount -o bind /dev/shm /data/dev/shm

        touch /data/chroot-ready
        chroot /data /bin/bash <<EOT
          set -x

          chpasswd <<<"$${USER}:$${XRDP_PASSWORD}"

          rm -rf /tmp/*
          rm -rf /tmp/.*
          rm /var/run/xrdp/xrdp-sesman.pid

          export LANG=C.UTF-8
          export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          export USER=$${USER}


          if [ ! -f /home/$${USER}/init.sh ]; then
            echo "#! /bin/bash" > /home/$${USER}/init.sh
            echo "sudo service xrdp restart" >> /home/$${USER}/init.sh

            chmod +x /home/$${USER}/init.sh
            chown $${USER}:$${USER} /home/$${USER}/init.sh
          fi

          if [ -x /home/$${USER}/init.sh ]; then
            runuser -l $${USER} /home/$${USER}/init.sh
          fi

          chmod 666 /dev/ptmx

          # can't find a way to declare and use a bash var here :(
          if [ -n "$${SSHD_KEYS_URL}" ] && [ -n "$${SSHD_PASSWORD}" ]; then
            runuser -l $${USER} -c "rospo sshd -P $${SSHD_LISTEN_ADDRESS} -K $${SSHD_KEYS_URL} -A $${SSHD_PASSWORD}"
          elif [ -n "$${SSHD_KEYS_URL}" ]; then
            runuser -l $${USER} -c "rospo sshd -P $${SSHD_LISTEN_ADDRESS} -K $${SSHD_KEYS_URL}"
          elif [ -n "$${SSHD_PASSWORD}" ]; then
            runuser -l $${USER} -c "rospo sshd -P $${SSHD_LISTEN_ADDRESS} -A $${SSHD_PASSWORD}"
          fi
        EOT


    